#!/bin/sh

###Установка curl
opkg update
opkg remove kmod-ipt-nat
opkg install curl luci-i18n-base-ru luci-i18n-commands-ru luci-i18n-firewall-ru luci-i18n-opkg-ru luci-i18n-ttyd-ru kmod-nls-cp866 kmod-nls-utf8 kmod-nls-cp1251 kmod-nf-nat tailscale tailscaled

###Фикс DPI-дурилок (Zapret, YouTubeUnblock) с Hardware/Software Offloading
sed -i 's/meta l4proto { tcp, udp } flow offload @ft;/meta l4proto { tcp, udp } ct original packets ge 30 flow offload @ft;/g' /usr/share/firewall4/templates/ruleset.uc

###Отключение QUIC на роутере (решает проблемы с видеопотоком, dpi обходами)
uci add firewall rule
uci set firewall.@rule[-1].name='Block_UDP_80'
uci set firewall.@rule[-1].src='*'
uci set firewall.@rule[-1].dest_port='80'
uci set firewall.@rule[-1].proto='udp'
uci set firewall.@rule[-1].target='REJECT'

uci add firewall rule
uci set firewall.@rule[-1].name='Block_UDP_443'
uci set firewall.@rule[-1].src='*'
uci set firewall.@rule[-1].dest_port='443'
uci set firewall.@rule[-1].proto='udp'
uci set firewall.@rule[-1].target='REJECT'

uci commit firewall
/etc/init.d/firewall restart

###🔧 Скрипт для отключения IPv6
curl -fsSL https://raw.githubusercontent.com/ilnur1111/routerr/refs/heads/main/disable_ipv6.sh | sh

###🚀 Установка Podkop
sh <(wget -O - https://raw.githubusercontent.com/itdoginfo/podkop/refs/heads/main/install.sh)

###🚀 Универсальный скрипт для YouTubeUnblock
curl -fsSL https://raw.githubusercontent.com/gfreemoon/install_youtubeunblock_universal/refs/heads/main/install%2Bconfig.sh | sh
